paths:
  data: "J:\\GBW-0051_IP3 Group\\Rita\\Jens\\20210218_Hela Fura Jens"
  calibrated: "J:\\GBW-0051_IP3 Group\\Rita\\Jens\\20210218_Hela Fura Jens\\Calibrated"
  plots: "J:\\GBW-0051_IP3 Group\\Rita\\Jens\\20210218_Hela Fura Jens\\Raw_plots"
constants:
  min_start_time: 200
  min_end_time: 211
  max_start_time: 250
  max_end_time: 325
# write null if you want to exectute the script for all data files in your path
filename: "20210218_KO_CISD2_ATP_1 analysis.xlsx"
