paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_microscope\\20200716-Jens-ATP-CISD2KOHeLaT1\\Raw"
  calibrated: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_microscope\\20200716-Jens-ATP-CISD2KOHeLaT1\\Calibrated"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\Ca2+_FURA_microscope\\20200716-Jens-ATP-CISD2KOHeLaT1\\Raw_plots"
constants:
  example_bool: False
  min_start_time: 690
  min_end_time: 735
  max_start_time: 735
  max_end_time: 861
filename: "202007126-2.5um_ATPHeLa T1 KO pool-4.csv"
