paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210218-TrexCISD2-FURA-RerCEPIA-Ca2+-Chen\\Analysis"
  plots: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210218-TrexCISD2-FURA-RerCEPIA-Ca2+-Chen\\Traces"
# write null if you want to execute the script for all data files in your path
filename: "202007126-2.5um_ATPHeLa T1 KO pool-4.csv"
