paths:
  data: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210218-TrexCISD2-FURA-RerCEPIA-Ca2+-Chen\\Quantification"
  SOICR: "C:\\Users\\u0132307\\Box Sync\\PhD\\Data\\NIKON\\20210218-TrexCISD2-FURA-RerCEPIA-Ca2+-Chen\\Quantification\\SOICR"
constants:
  threshold_start_time: 40
  threshold_end_time: 300
  cut_off_percentage: 0.01
  tetracaine_start_time: 60
  tetracaine_end_time: 100
  caffeine_start_time:
  caffeine_end_time:
filename: "20210218-KO1-CISD2.xlsx"